"""Create vehicles table

Revision ID: 1e007164810a
Revises: 892c13180075
Create Date: 2024-03-24 16:00:58.344024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e007164810a'
down_revision: Union[str, None] = '892c13180075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.add_column('regions', sa.Column('vehicle_external_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'regions', 'vehicles', ['vehicle_external_id'], ['external_id'])
    op.drop_column('regions', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'regions', type_='foreignkey')
    op.drop_column('regions', 'vehicle_external_id')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
