"""rename state to make

Revision ID: c4b4c1a079ea
Revises: ca736e6eeef3
Create Date: 2024-04-14 13:00:47.925212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b4c1a079ea'
down_revision: Union[str, None] = 'ca736e6eeef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('make', sa.String(), nullable=True))
    op.drop_column('vehicles', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('vehicles', 'make')
    # ### end Alembic commands ###
