"""Update Regions

Revision ID: ca736e6eeef3
Revises: 1e007164810a
Create Date: 2024-03-25 21:37:27.434493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca736e6eeef3'
down_revision: Union[str, None] = '1e007164810a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('vehicle_id', sa.Integer(), nullable=False))
    op.add_column('regions', sa.Column('frame_id', sa.String(), nullable=False))
    op.drop_constraint('regions_vehicle_external_id_fkey', 'regions', type_='foreignkey')
    op.create_foreign_key(None, 'regions', 'vehicles', ['vehicle_id'], ['id'])
    op.drop_column('regions', 'vehicle_external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('vehicle_external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'regions', type_='foreignkey')
    op.create_foreign_key('regions_vehicle_external_id_fkey', 'regions', 'vehicles', ['vehicle_external_id'], ['external_id'])
    op.drop_column('regions', 'frame_id')
    op.drop_column('regions', 'vehicle_id')
    # ### end Alembic commands ###
