"""add orientation to Camera

Revision ID: f485f969dccf
Revises: 83aa55f47c82
Create Date: 2024-04-28 19:37:34.552880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f485f969dccf'
down_revision: Union[str, None] = '83aa55f47c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('orientation', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'orientation')
    # ### end Alembic commands ###
