version: '3.9'

services:
  stream-consumer:
    container_name: 'stream-consumer'
    image: "itsop/roadtrace-stream-consumer:latest"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
                - utility
                - compute
    volumes:
      - ./streamConsumer/Artifacts:/usr/src/Artifacts
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
  
  data-extractor:
    container_name: 'data-extractor'
    image: "itsop/roadtrace-data-extractor:latest"
    depends_on:
      - stream-consumer
      - postgres
      - rabbitmq
    env_file:
      - .env
  
  analytics:
    container_name: 'analytics'
    image: "itsop/roadtrace-analytics:latest"
    depends_on:
      - stream-consumer
      - redis
    ports:
      - 5000:80
    env_file:
      - .env

  rabbitmq:
    container_name: 'rabbitmq'
    image: "rabbitmq:3-management"
    env_file:
      - .env
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management interface
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
  redis:
    image: redislabs/redistimeseries:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  rabbitmq_data:
    driver: local
  local_pgdata:
  redis-data:
