version: '3.9'

services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management interface
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
  redis:
    image: redislabs/redistimeseries:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  rabbitmq_data:
    driver: local
  local_pgdata:
  redis-data:
